//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEstadoPuesto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificacionEvento", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    public partial class NotificacionEvento : object
    {
        
        private string CodigoDispositivoField;
        
        private string CodigoEventoField;
        
        private System.Collections.Generic.Dictionary<string, string> DatosField;
        
        private System.Collections.Generic.Dictionary<string, decimal> ValoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDispositivo
        {
            get
            {
                return this.CodigoDispositivoField;
            }
            set
            {
                this.CodigoDispositivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEvento
        {
            get
            {
                return this.CodigoEventoField;
            }
            set
            {
                this.CodigoEventoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, decimal> Valores
        {
            get
            {
                return this.ValoresField;
            }
            set
            {
                this.ValoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConcentradorDto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Scato.Dominio.Dto")]
    public partial class ConcentradorDto : object
    {
        
        private string ConcentradorField;
        
        private ServicioEstadoPuesto.ConfigSensoresDto ConfigSensoresField;
        
        private ServicioEstadoPuesto.EstadoSensoresBalanzaDto EstadoSensoresBalanzaDtoField;
        
        private int PuestoIdField;
        
        private ServicioEstadoPuesto.DispositivoGenericoDto[] SensoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Concentrador
        {
            get
            {
                return this.ConcentradorField;
            }
            set
            {
                this.ConcentradorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioEstadoPuesto.ConfigSensoresDto ConfigSensores
        {
            get
            {
                return this.ConfigSensoresField;
            }
            set
            {
                this.ConfigSensoresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioEstadoPuesto.EstadoSensoresBalanzaDto EstadoSensoresBalanzaDto
        {
            get
            {
                return this.EstadoSensoresBalanzaDtoField;
            }
            set
            {
                this.EstadoSensoresBalanzaDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuestoId
        {
            get
            {
                return this.PuestoIdField;
            }
            set
            {
                this.PuestoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioEstadoPuesto.DispositivoGenericoDto[] Sensores
        {
            get
            {
                return this.SensoresField;
            }
            set
            {
                this.SensoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigSensoresDto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Scato.Dominio.Dto")]
    public partial class ConfigSensoresDto : object
    {
        
        private int Centro_IdField;
        
        private string DescripcionField;
        
        private int IdField;
        
        private string SensorBarreraEntradaAbajoField;
        
        private string SensorBarreraEntradaArribaField;
        
        private string SensorBarreraSalidaAbajoField;
        
        private string SensorBarreraSalidaArribaField;
        
        private string SensorPosicionIngresoField;
        
        private string SensorPosicionSalidaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Centro_Id
        {
            get
            {
                return this.Centro_IdField;
            }
            set
            {
                this.Centro_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorBarreraEntradaAbajo
        {
            get
            {
                return this.SensorBarreraEntradaAbajoField;
            }
            set
            {
                this.SensorBarreraEntradaAbajoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorBarreraEntradaArriba
        {
            get
            {
                return this.SensorBarreraEntradaArribaField;
            }
            set
            {
                this.SensorBarreraEntradaArribaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorBarreraSalidaAbajo
        {
            get
            {
                return this.SensorBarreraSalidaAbajoField;
            }
            set
            {
                this.SensorBarreraSalidaAbajoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorBarreraSalidaArriba
        {
            get
            {
                return this.SensorBarreraSalidaArribaField;
            }
            set
            {
                this.SensorBarreraSalidaArribaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorPosicionIngreso
        {
            get
            {
                return this.SensorPosicionIngresoField;
            }
            set
            {
                this.SensorPosicionIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorPosicionSalida
        {
            get
            {
                return this.SensorPosicionSalidaField;
            }
            set
            {
                this.SensorPosicionSalidaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoSensoresBalanzaDto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Scato.Dominio.Dto")]
    public partial class EstadoSensoresBalanzaDto : object
    {
        
        private bool BarreraEntradaActivaField;
        
        private bool BarreraEntradaDesactivaField;
        
        private bool BarreraSalidaActivaField;
        
        private bool BarreraSalidaDesactivaField;
        
        private int PuestoIdField;
        
        private int SensorDireccionIdField;
        
        private bool SensorIngresoActivaField;
        
        private string SensorModificadoField;
        
        private bool SensorTrompaActivaField;
        
        private bool SensorVagonStatusField;
        
        private bool SensorVagonesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BarreraEntradaActiva
        {
            get
            {
                return this.BarreraEntradaActivaField;
            }
            set
            {
                this.BarreraEntradaActivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BarreraEntradaDesactiva
        {
            get
            {
                return this.BarreraEntradaDesactivaField;
            }
            set
            {
                this.BarreraEntradaDesactivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BarreraSalidaActiva
        {
            get
            {
                return this.BarreraSalidaActivaField;
            }
            set
            {
                this.BarreraSalidaActivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BarreraSalidaDesactiva
        {
            get
            {
                return this.BarreraSalidaDesactivaField;
            }
            set
            {
                this.BarreraSalidaDesactivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuestoId
        {
            get
            {
                return this.PuestoIdField;
            }
            set
            {
                this.PuestoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SensorDireccionId
        {
            get
            {
                return this.SensorDireccionIdField;
            }
            set
            {
                this.SensorDireccionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SensorIngresoActiva
        {
            get
            {
                return this.SensorIngresoActivaField;
            }
            set
            {
                this.SensorIngresoActivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorModificado
        {
            get
            {
                return this.SensorModificadoField;
            }
            set
            {
                this.SensorModificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SensorTrompaActiva
        {
            get
            {
                return this.SensorTrompaActivaField;
            }
            set
            {
                this.SensorTrompaActivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SensorVagonStatus
        {
            get
            {
                return this.SensorVagonStatusField;
            }
            set
            {
                this.SensorVagonStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SensorVagones
        {
            get
            {
                return this.SensorVagonesField;
            }
            set
            {
                this.SensorVagonesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispositivoGenericoDto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Scato.Dominio.Dto")]
    public partial class DispositivoGenericoDto : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEstadoPuesto.IServicioEstadoPuesto")]
    public interface IServicioEstadoPuesto
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/ActualizarPuestos", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/ActualizarPuestosResponse")]
        System.Threading.Tasks.Task ActualizarPuestosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/NotificarCambioDeEstado", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/NotificarCambioDeEstadoResponse")]
        System.Threading.Tasks.Task NotificarCambioDeEstadoAsync(string concentrador, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/ValidarEstadoPuesto", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/ValidarEstadoPuestoResponse")]
        System.Threading.Tasks.Task<bool> ValidarEstadoPuestoAsync(int puestoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/NotificarSensorBarrera", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/NotificarSensorBarreraResponse")]
        System.Threading.Tasks.Task NotificarSensorBarreraAsync(ServicioEstadoPuesto.NotificacionEvento notificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/NotificarEstado", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/NotificarEstadoResponse")]
        System.Threading.Tasks.Task NotificarEstadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/ConsultarEstadoBarreras", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/ConsultarEstadoBarrerasResponse")]
        System.Threading.Tasks.Task<ServicioEstadoPuesto.ConcentradorDto[]> ConsultarEstadoBarrerasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/ActualizarBarreras", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/ActualizarBarrerasResponse")]
        System.Threading.Tasks.Task ActualizarBarrerasAsync(string nombrePc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPuesto/NotificarSensorBarreraHidraulicas", ReplyAction="http://tempuri.org/IServicioEstadoPuesto/NotificarSensorBarreraHidraulicasRespons" +
            "e")]
        System.Threading.Tasks.Task NotificarSensorBarreraHidraulicasAsync(ServicioEstadoPuesto.NotificacionEvento notificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioEstadoPuestoChannel : ServicioEstadoPuesto.IServicioEstadoPuesto, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioEstadoPuestoClient : System.ServiceModel.ClientBase<ServicioEstadoPuesto.IServicioEstadoPuesto>, ServicioEstadoPuesto.IServicioEstadoPuesto
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEstadoPuestoClient() : 
                base(ServicioEstadoPuestoClient.GetDefaultBinding(), ServicioEstadoPuestoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEstadoPuesto.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadoPuestoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEstadoPuestoClient.GetBindingForEndpoint(endpointConfiguration), ServicioEstadoPuestoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadoPuestoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEstadoPuestoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadoPuestoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEstadoPuestoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadoPuestoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task ActualizarPuestosAsync()
        {
            return base.Channel.ActualizarPuestosAsync();
        }
        
        public System.Threading.Tasks.Task NotificarCambioDeEstadoAsync(string concentrador, string mensaje)
        {
            return base.Channel.NotificarCambioDeEstadoAsync(concentrador, mensaje);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarEstadoPuestoAsync(int puestoId)
        {
            return base.Channel.ValidarEstadoPuestoAsync(puestoId);
        }
        
        public System.Threading.Tasks.Task NotificarSensorBarreraAsync(ServicioEstadoPuesto.NotificacionEvento notificacion)
        {
            return base.Channel.NotificarSensorBarreraAsync(notificacion);
        }
        
        public System.Threading.Tasks.Task NotificarEstadoAsync()
        {
            return base.Channel.NotificarEstadoAsync();
        }
        
        public System.Threading.Tasks.Task<ServicioEstadoPuesto.ConcentradorDto[]> ConsultarEstadoBarrerasAsync()
        {
            return base.Channel.ConsultarEstadoBarrerasAsync();
        }
        
        public System.Threading.Tasks.Task ActualizarBarrerasAsync(string nombrePc)
        {
            return base.Channel.ActualizarBarrerasAsync(nombrePc);
        }
        
        public System.Threading.Tasks.Task NotificarSensorBarreraHidraulicasAsync(ServicioEstadoPuesto.NotificacionEvento notificacion)
        {
            return base.Channel.NotificarSensorBarreraHidraulicasAsync(notificacion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstadoPuesto))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstadoPuesto))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/Scato.ServiciosWeb/ServicioEstadoPuesto.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEstadoPuestoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEstadoPuesto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEstadoPuestoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEstadoPuesto);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEstadoPuesto,
        }
    }
}
